name: just_store_clean
description: A student-focused marketplace app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Animations
  animated_widgets: ^1.1.0
  flutter_staggered_animations: ^1.1.1

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.6
  cloud_functions: ^4.5.3


  # HTTP for Cloudinary
  http: ^1.2.1

  # Media
  image_picker: ^1.0.7

  # UI & Icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0

  # State management
  provider: ^6.1.1

  # Local storage
  shared_preferences: ^2.2.2

  # File system
  path_provider: ^2.1.2
  path: ^1.8.3

  # Notifications
  flutter_local_notifications: ^19.1.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Sharing
  share_plus: ^7.2.1

  # Verify code and URL handling
  pin_code_fields: ^8.0.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/